export const TOGGLE_BOOK = "TOGGLE_BOOK";
export const TOGGLE_COMPOSER = "TOGGLE_COMPOSER";
export const TOGGLE_GENRE = "TOGGLE_GENRE";
export const SET_PLAYLIST = "SET_PLAYLIST";
export const SET_FILTER = "SET_FILTER";

export const TOGGLE_SPOTIFY_SETTINGS = "TOGGLE_SPOTIFY_SETTINGS";
export const OPEN_SPOTIFY_SETTINGS = "OPEN_SPOTIFY_SETTINGS";
export const CLOSE_SPOTIFY_SETTINGS = "CLOSE_SPOTIFY_SETTINGS";

export const RE_LOGIN_PROMPT = "RE_LOGIN_PROMPT";

export const CREATE_PLAYLIST = "CREATE_PLAYLIST";

export const REQUEST_TRACK_INFO = "REQUEST_TRACK_INFO";
export const RECEIVE_TRACK_INFO = "RECEIVE_TRACK_INFO";

export const SET_SPOTIFY_USER_ID = "SET_SPOTIFY_USER_ID";

export const CURRENTLY_PLAYING_TRACK = "CURRENTLY_PLAYING_TRACK";
export const CURRENTLY_PLAYING_PLAYLIST = "CURRENTLY_PLAYING_PLAYLIST";

export const FETCH_TRACK_INFO_SUCCESS = "FETCH_TRACK_INFO_SUCCESS";
export const FETCH_TRACK_INFO_FAILURE = "TRACK_INFO_FAILURE";

export const PLAYLIST_CREATION_FAILURE = "PLAYLIST_CREATION_FAILURE";
export const PLAYLIST_CREATION_SUCCESS = "PLAYLIST_CREATION_SUCCESS";