export const REQUEST_REFERENCES = "REQUEST_REFERNCES";
export const RECEIVE_REFERENCES = "RECEIVE_REFERENCES";
export const TOGGLE_BOOK = "TOGGLE_BOOK";
export const TOGGLE_COMPOSER = "TOGGLE_COMPOSER";
export const TOGGLE_GENRE = "TOGGLE_GENRE";
export const SET_FILTER = "SET_FILTER";